version: '3.9'

services:
  api:
    build:
      context: .
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
  postgres:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB}
    ports:
      - "5430:5430"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
